# Generated by Django 5.2.17 on 2026-09-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founderinfo',
            old_name='contact_info',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='founderinfo',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='founderinfo',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='founderinfo',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='founderinfo',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country_and_city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='passport_photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sex',
        ),
        migrations.AddField(
            model_name='founderinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='founderinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='founder/'),
        ),
        migrations.AddField(
            model_name='founderinfo',
            name='name',
            field=models.CharField(default='Admin', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='founderinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
