# Generated by Django 5.2.17 on 2026-09-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_contact_info_founderinfo_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passports/'),
        ),
    ]
