# Generated by Django 5.2.17 on 2026-09-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile_passport_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founderinfo',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='founderinfo',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='founder/'),
        ),
        migrations.AddField(
            model_name='founderinfo',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='founder/'),
        ),
    ]
